AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'features/support/env.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'spec/teaspoon_env.rb'
    - 'lib/tasks/cucumber.rake'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/RedundantSelf:
  Enabled: false

Style/TrailingBlankLines:
  EnforcedStyle: final_newline
  Enabled: true
